import { expect, test } from '@playwright/test'

test.describe('Connect Four lifecycle and review', () => {
  test.skip(({ browserName, isMobile }) => browserName !== 'chromium' || isMobile, 'Lifecycle runs once on desktop Chromium')

  test('restart, resignation focus, rematch setup, and review of a prior move', async ({ page }) => {
    await page.addInitScript(() => { Math.random = () => 0 })
    await page.goto('')
    await page.getByRole('button', { name: 'Connect Four' }).click()
    await page.getByRole('button', { name: 'Play as yellow' }).click()
    await page.getByRole('button', { name: 'Start game' }).click()
    await expect(page.getByRole('button', { name: 'Restart' })).toBeVisible()
    await page.getByRole('button', { name: 'Restart' }).click()
    await expect(page.locator('.cf-history-entry')).toHaveCount(0)
    await page.getByRole('button', { name: 'B1, empty' }).click()
    await expect(page.locator('.cf-history-entry')).toHaveCount(2)
    await page.getByRole('button', { name: 'Review moves' }).click()
    await expect(page.getByRole('group', { name: 'Historical Connect Four board' })).toBeVisible()
    await page.getByRole('button', { name: 'Earlier' }).click()
    await expect(page.locator('.cf-inspection-title')).toHaveText('Historical position after 1y B1')
    await expect(page.getByRole('button', { name: 'A1, empty' })).toBeVisible()
    await page.getByRole('button', { name: 'Return to current' }).click()
    await expect(page.getByRole('group', { name: 'Current Connect Four board' })).toBeVisible()
    const resign = page.getByRole('button', { name: 'Resign' })
    await resign.focus()
    await resign.click()
    await expect(page.getByRole('dialog', { name: 'Resign this match?' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(resign).toBeFocused()
    await resign.click()
    await page.getByRole('dialog', { name: 'Resign this match?' }).getByRole('button', { name: 'Resign' }).click()
    await expect(page.getByText('Defeat', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Rematch' }).click()
    await expect(page.getByRole('heading', { name: 'Set up Connect Four' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Play as yellow' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('button', { name: 'Chess' })).toBeDisabled()
  })
})
